print("Adding Two Numbers!")
a = int(input("Enter First Number: "))
b = int(input("Enter Second Number: "))
print("The Addition is:",a+b)
print("The Subtraction is:",a-b)
print("The Multiplication is:",a*b)
print("The Division is:",a/b)